/* Generated by gbrecomp */
#ifndef tlozoos_H
#define tlozoos_H

#include "gbrt.h"

const GBConfig* tlozoos_default_config(void);
void tlozoos_run(GBContext* ctx);
void tlozoos_init(GBContext* ctx);
int tlozoos_main(int argc, char* argv[]);

#endif
